version: '3.7'
services:
  # influxdb:
  #   image: influxdb:2.5-alpine
  #   container_name: influxdb
  #   ports:
  #     - 8086:8086
  #   environment:
  #     - DOCKER_INFLUXDB_INIT_USERNAME=root
  #     - DOCKER_INFLUXDB_INIT_PASSWORD=root@2022
  #     - DOCKER_INFLUXDB_INIT_ORG=iot
  #     - DOCKER_INFLUXDB_INIT_BUCKET=bucket
  #   volumes:
  #     - ./influxdb:/imports
  #     - ./influxdb/influxdb_data:/var/lib/influxdb

  telegraf:
    image: telegraf:1.24-alpine
    container_name: telegraf
    ports:
      - 8125:8125/udp
    depends_on:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:rw
